
package javaminor.SOAPclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentImplService", targetNamespace = "http://service/", wsdlLocation = "file:///home/alex/git/POScaseREST/src/main/java/javaminor/SOAPclient/PaymentPOS.wsdl")
public class PaymentImplService
    extends Service
{

    private final static URL PAYMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTIMPLSERVICE_EXCEPTION;
    private final static QName PAYMENTIMPLSERVICE_QNAME = new QName("http://service/", "PaymentImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///home/alex/git/POScaseREST/src/main/java/javaminor/SOAPclient/PaymentPOS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTIMPLSERVICE_WSDL_LOCATION = url;
        PAYMENTIMPLSERVICE_EXCEPTION = e;
    }

    public PaymentImplService() {
        super(__getWsdlLocation(), PAYMENTIMPLSERVICE_QNAME);
    }

    public PaymentImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTIMPLSERVICE_QNAME, features);
    }

    public PaymentImplService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTIMPLSERVICE_QNAME);
    }

    public PaymentImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTIMPLSERVICE_QNAME, features);
    }

    public PaymentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentImpl
     */
    @WebEndpoint(name = "PaymentImplPort")
    public PaymentImpl getPaymentImplPort() {
        return super.getPort(new QName("http://service/", "PaymentImplPort"), PaymentImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentImpl
     */
    @WebEndpoint(name = "PaymentImplPort")
    public PaymentImpl getPaymentImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "PaymentImplPort"), PaymentImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTIMPLSERVICE_EXCEPTION!= null) {
            throw PAYMENTIMPLSERVICE_EXCEPTION;
        }
        return PAYMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
