
package javaminor.SOAPclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentImpl", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCard", targetNamespace = "http://service/", className = "javaminor.SOAPclient.ValidateCard")
    @ResponseWrapper(localName = "validateCardResponse", targetNamespace = "http://service/", className = "javaminor.SOAPclient.ValidateCardResponse")
    @Action(input = "http://service/PaymentImpl/validateCardRequest", output = "http://service/PaymentImpl/validateCardResponse")
    public boolean validateCard(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://service/", className = "javaminor.SOAPclient.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://service/", className = "javaminor.SOAPclient.PayResponse")
    @Action(input = "http://service/PaymentImpl/payRequest", output = "http://service/PaymentImpl/payResponse")
    public boolean pay(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
